# Generated by Django 3.1.5 on 2021-03-03 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0004_auto_20210303_1241'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Razão social da empresa.', max_length=255, verbose_name='Razão social')),
                ('fantasy_name', models.CharField(help_text='Nome fantasia da empresa.', max_length=255, verbose_name='Nome fantasia')),
                ('state', models.CharField(help_text='Sigla do estado da empresa.', max_length=2, verbose_name='Estado')),
                ('cnpj', models.CharField(help_text='Nº do CNPJ da empresa.', max_length=14, unique=True, verbose_name='Nº CNPJ')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Criado em', verbose_name='Criado em')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Atualizado em', null=True, verbose_name='Atualizado em')),
                ('legal_owners', models.ManyToManyField(related_name='companies', to='companies.Company', verbose_name='Donos pessoas jurídicas')),
                ('physical_owners', models.ManyToManyField(related_name='companies', to='persons.Person', verbose_name='Donos pessoas físicas')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='companies_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='companies_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['-date_created'],
            },
        ),
    ]
