# Generated by Django 3.1.5 on 2021-03-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_auto_20210303_1644'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='cnpj',
            new_name='_cnpj',
        ),
        migrations.AlterField(
            model_name='company',
            name='_cnpj',
            field=models.CharField(db_column='cnpj', help_text='Nº do CNPJ da empresa.', max_length=14, unique=True, verbose_name='Nº CNPJ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_owners',
            field=models.ManyToManyField(related_name='companies_owned', to='companies.Company', verbose_name='Donos pessoas jurídicas'),
        ),
        migrations.AlterField(
            model_name='company',
            name='physical_owners',
            field=models.ManyToManyField(related_name='companies_owned', to='persons.Person', verbose_name='Donos pessoas físicas'),
        ),
    ]
