#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate

# Create initial local user
echo "
from django.contrib.auth import get_user_model;

User = get_user_model();
if User.objects.count() == 0:
    User.objects.create_superuser(username='admin', email='admin@admin.com', password='admin')
    User.objects.create_user(username='test', password='test')
" | python manage.py shell

python manage.py collectstatic --noinput
python manage.py runserver_plus 0.0.0.0:8000
