# Generated by Django 3.1.5 on 2021-03-02 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persons', '0002_auto_20210302_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='Criado em', verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, help_text='Atualizado em', null=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='persons_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='persons_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por'),
        ),
    ]
