# Generated by Django 3.1.5 on 2021-03-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20210302_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(help_text='Nº do CPF da pessoa.', max_length=14, unique=True, verbose_name='Nº CPF'),
        ),
    ]
