# Generated by Django 3.1.5 on 2021-03-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_auto_20210303_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='cpf',
            new_name='_cpf',
        ),
        migrations.AlterField(
            model_name='person',
            name='_cpf',
            field=models.CharField(db_column='cpf', help_text='Nº do CPF da pessoa.', max_length=14, unique=True, verbose_name='Nº CPF'),
        ),
    ]
