# Generated by Django 3.1.5 on 2021-03-04 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persons', '0006_auto_20210303_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da posse.', max_length=255, verbose_name='Nome')),
                ('value', models.FloatField(default=0, help_text='Valor total da posse.', verbose_name='Valor')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Criado em', verbose_name='Criado em')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Atualizado em', null=True, verbose_name='Atualizado em')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='persons.person', verbose_name='Proprietário')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ownerships_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ownerships_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Posse',
                'verbose_name_plural': 'Posses',
                'ordering': ['-date_created'],
            },
        ),
    ]
